<?php

namespace App;

use App\Models\Attachment;
use App\Models\Notification;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Cashier\Billable;

class User extends Authenticatable
{
    use Notifiable, Billable;
    protected $table='users';
    protected $primaryKey='user_id';
    const ROLE = [
        'Admin'=>1,
        'Member'=>2,
    ];

    const STATUS=[
        'Active'=>1,
        'Inactive'=>2,
        'Expired'=>3,
    ];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'status',
        'avatar_id',
        'user_name',
        'phone_no',
        'stripe_id',
        'stripe_product_id',
        'stripe_plan_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getForeignKey()
    {
        return $this->getKeyName(); // TODO: Change the autogenerated stub
    }

    public function avatar()
    {
        return $this->hasOne(Attachment::class, 'attachment_id', 'avatar_id');
    }

    public function notifications()
    {
        return $this->hasMany(Notification::class, 'user_id');
    }
}
